### ISSUE TITLE
Add awkard extension array to pandas ecosystem docs

### ISSUE THREAD

**Issue by mroeschke** [intake/awkward-pandas#11]
I stumbled upon the demo for the extensionarray, https://github.com/intake/awkward-pandas/tree/main/demo, very cool! 

Would be great to advertise in the pandas ecosystem docs when deemed ready: https://pandas.pydata.org/docs/ecosystem.html

**Comment by martindurant** [comment]
Thanks for checking in @mroeschke ! We made a few tweaks and worked up this demo in the last couple of days to show some people at Anaconda, and had intended to get in touch with you next week to get your thoughts. While we have a number of interesting things working, there are probably both problems with a number of things we are doing which you might notice (e.g., accidental iteration instead of vectorised operations), but there are also bigger questions around integrating with user experience and existing arrow storage/tools/string ops.

**Comment by mroeschke** [comment]
Sounds good. I'll try to carve out some time next week to check out the progress independently too.

**Comment by martindurant** [comment]
Eagerly awaiting your thoughts! Also, this would be a good time to enumerate example workflows which you may have to hand, so that we can turn them into examples.
